import RequestProject.Zeta35.DenCertCheck

/-! Generated by `scripts/gen_cert_c35.py` from `certificates/cert_c_p3_q4_d1_a1.5_k6.0.json`:
subcells 2832–2879 (records `(b, λ, h, q, br, S₀)`), checked by kernel
evaluation (`decide +kernel`). -/

namespace Zeta35.Den.CertData

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Subcell records. -/
def b59 : List SubRec := [
  (49/16, 0, 12, 0, true, [0, 3, 0, 0]),
  (25/8, 0, 23/2, 0, true, [0, 3, 0, 0]),
  (51/16, 0, 11, 0, true, [0, 3, 0, 0]),
  (13/4, 0, 21/2, 0, true, [0, 3, 0, 0]),
  (53/16, 0, 10, 0, true, [0, 3, 0, 0]),
  (27/8, 0, 19/2, 0, true, [0, 3, 0, 0]),
  (55/16, 0, 9, 0, true, [0, 3, 0, 0]),
  (7/2, 0, 17/2, 0, true, [0, 3, 0, 0]),
  (57/16, 0, 8, 0, true, [0, 3, 0, 0]),
  (29/8, 0, 15/2, 0, true, [0, 3, 0, 0]),
  (59/16, 0, 7, 0, true, [0, 3, 0, 0]),
  (15/4, 0, 13/2, 0, true, [0, 3, 0, 0]),
  (61/16, 0, 6, 0, true, [0, 3, 0, 0]),
  (31/8, 0, 11/2, 0, true, [0, 3, 0, 0]),
  (63/16, 0, 5, 0, true, [0, 3, 0, 0]),
  (4, 0, 9/2, 0, true, [0, 3, 0, 0]),
  (65/16, 0, 4, 0, true, [0, 3, 0, 0]),
  (33/8, 0, 7/2, 0, true, [0, 3, 0, 0]),
  (67/16, 0, 3, 0, true, [0, 3, 0, 0]),
  (17/4, 0, 5/2, 0, true, [0, 3, 0, 0]),
  (69/16, 0, 2, 0, true, [0, 3, 0, 0]),
  (35/8, 0, 3/2, 0, true, [0, 3, 0, 0]),
  (71/16, 0, 1, 0, true, [0, 3, 0, 0]),
  (9/2, 0, 1/2, 0, true, [0, 3, 0, 0]),
  (217/48, 0, 0, 0, false, [0, 3, 0, 0]),
  (109/24, 0, 0, 0, false, [0, 3, 0, 0]),
  (73/16, 0, 0, 0, false, [0, 3, 0, 0]),
  (55/12, 0, 0, 0, false, [0, 3, 0, 0]),
  (221/48, 0, 0, 0, false, [0, 3, 0, 0]),
  (37/8, 0, 0, 0, false, [0, 3, 0, 0]),
  (223/48, 0, 0, 0, false, [0, 3, 0, 0]),
  (14/3, 0, 0, 0, false, [0, 3, 0, 0]),
  (75/16, 0, 0, 0, false, [0, 3, 0, 0]),
  (113/24, 0, 0, 0, false, [0, 3, 0, 0]),
  (227/48, 0, 0, 0, false, [0, 3, 0, 0]),
  (19/4, 0, 0, 0, false, [0, 3, 0, 0]),
  (229/48, 0, 0, 0, false, [0, 3, 0, 0]),
  (115/24, 0, 0, 0, false, [0, 3, 0, 0]),
  (77/16, 0, 0, 0, false, [0, 3, 0, 0]),
  (29/6, 0, 0, 0, false, [0, 3, 0, 0]),
  (233/48, 0, 0, 0, false, [0, 3, 0, 0]),
  (39/8, 0, 0, 0, false, [0, 3, 0, 0]),
  (235/48, 0, 0, 0, false, [0, 3, 0, 0]),
  (59/12, 0, 0, 0, false, [0, 3, 0, 0]),
  (79/16, 0, 0, 0, false, [0, 3, 0, 0]),
  (119/24, 0, 0, 0, false, [0, 3, 0, 0]),
  (239/48, 0, 0, 0, false, [0, 3, 0, 0]),
  (5, 0, 0, 0, false, [0, 3, 0, 0])]

set_option maxRecDepth 100000 in
theorem b59_ok : chainOK (3) b59 = true := by decide +kernel

set_option maxRecDepth 100000 in
theorem b59_last : lastB (3) b59 = 5 := by decide +kernel

set_option maxRecDepth 100000 in
theorem b59_sum : stepSum (3) b59 ≤ 75/8 := by decide +kernel

theorem b59_blk : Blk (3) b59 (5) (75/8) :=
  ⟨b59_ok, b59_last, b59_sum⟩

end Zeta35.Den.CertData
