import RequestProject.Zeta35.CertData.B0
import RequestProject.Zeta35.CertData.B1
import RequestProject.Zeta35.CertData.B2
import RequestProject.Zeta35.CertData.B3
import RequestProject.Zeta35.CertData.B4
import RequestProject.Zeta35.CertData.B5
import RequestProject.Zeta35.CertData.B6
import RequestProject.Zeta35.CertData.B7
import RequestProject.Zeta35.CertData.B8
import RequestProject.Zeta35.CertData.B9
import RequestProject.Zeta35.CertData.B10
import RequestProject.Zeta35.CertData.B11
import RequestProject.Zeta35.CertData.B12
import RequestProject.Zeta35.CertData.B13
import RequestProject.Zeta35.CertData.B14
import RequestProject.Zeta35.CertData.B15
import RequestProject.Zeta35.CertData.B16
import RequestProject.Zeta35.CertData.B17
import RequestProject.Zeta35.CertData.B18
import RequestProject.Zeta35.CertData.B19
import RequestProject.Zeta35.CertData.B20
import RequestProject.Zeta35.CertData.B21
import RequestProject.Zeta35.CertData.B22
import RequestProject.Zeta35.CertData.B23
import RequestProject.Zeta35.CertData.B24
import RequestProject.Zeta35.CertData.B25
import RequestProject.Zeta35.CertData.B26
import RequestProject.Zeta35.CertData.B27
import RequestProject.Zeta35.CertData.B28
import RequestProject.Zeta35.CertData.B29
import RequestProject.Zeta35.CertData.B30
import RequestProject.Zeta35.CertData.B31
import RequestProject.Zeta35.CertData.B32
import RequestProject.Zeta35.CertData.B33
import RequestProject.Zeta35.CertData.B34
import RequestProject.Zeta35.CertData.B35
import RequestProject.Zeta35.CertData.B36
import RequestProject.Zeta35.CertData.B37
import RequestProject.Zeta35.CertData.B38
import RequestProject.Zeta35.CertData.B39
import RequestProject.Zeta35.CertData.B40
import RequestProject.Zeta35.CertData.B41
import RequestProject.Zeta35.CertData.B42
import RequestProject.Zeta35.CertData.B43
import RequestProject.Zeta35.CertData.B44
import RequestProject.Zeta35.CertData.B45
import RequestProject.Zeta35.CertData.B46
import RequestProject.Zeta35.CertData.B47
import RequestProject.Zeta35.CertData.B48
import RequestProject.Zeta35.CertData.B49
import RequestProject.Zeta35.CertData.B50
import RequestProject.Zeta35.CertData.B51
import RequestProject.Zeta35.CertData.B52
import RequestProject.Zeta35.CertData.B53
import RequestProject.Zeta35.CertData.B54
import RequestProject.Zeta35.CertData.B55
import RequestProject.Zeta35.CertData.B56
import RequestProject.Zeta35.CertData.B57
import RequestProject.Zeta35.CertData.B58
import RequestProject.Zeta35.CertData.B59

/-!
# The certificate of N, Theorem 5.1 (generated by `scripts/gen_cert_c35.py`)

`certL` is the full list of the 60 kernel-checked blocks of subcells, covering
`[1/20, 5]`; **`certL_blk`**: the chain is checked, ends at `5`, and its step sum
`∑ h (b − a)` is at most `stepBound = 196761611117789/1000000000000` (≈ 196.761611118).
-/

namespace Zeta35.Den

open CertData

/-- The full certificate. -/
def certL : List SubRec := b0 ++ b1 ++ b2 ++ b3 ++ b4 ++ b5 ++ b6 ++ b7 ++ b8 ++ b9 ++ b10 ++ b11 ++ b12 ++ b13 ++ b14 ++ b15 ++ b16 ++ b17 ++ b18 ++ b19 ++ b20 ++ b21 ++ b22 ++ b23 ++ b24 ++ b25 ++ b26 ++ b27 ++ b28 ++ b29 ++ b30 ++ b31 ++ b32 ++ b33 ++ b34 ++ b35 ++ b36 ++ b37 ++ b38 ++ b39 ++ b40 ++ b41 ++ b42 ++ b43 ++ b44 ++ b45 ++ b46 ++ b47 ++ b48 ++ b49 ++ b50 ++ b51 ++ b52 ++ b53 ++ b54 ++ b55 ++ b56 ++ b57 ++ b58 ++ b59

/-- The bound on the step sum `∑ h_i (b_i − a_i)`. -/
def stepBound : ℚ := 196761611117789/1000000000000

set_option maxRecDepth 100000 in
/-- **The certificate is checked.** -/
theorem certL_blk : Blk (1/20) certL (5) stepBound := by
  have h := blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (blk_app (CertData.b0_blk) CertData.b1_blk) CertData.b2_blk) CertData.b3_blk) CertData.b4_blk) CertData.b5_blk) CertData.b6_blk) CertData.b7_blk) CertData.b8_blk) CertData.b9_blk) CertData.b10_blk) CertData.b11_blk) CertData.b12_blk) CertData.b13_blk) CertData.b14_blk) CertData.b15_blk) CertData.b16_blk) CertData.b17_blk) CertData.b18_blk) CertData.b19_blk) CertData.b20_blk) CertData.b21_blk) CertData.b22_blk) CertData.b23_blk) CertData.b24_blk) CertData.b25_blk) CertData.b26_blk) CertData.b27_blk) CertData.b28_blk) CertData.b29_blk) CertData.b30_blk) CertData.b31_blk) CertData.b32_blk) CertData.b33_blk) CertData.b34_blk) CertData.b35_blk) CertData.b36_blk) CertData.b37_blk) CertData.b38_blk) CertData.b39_blk) CertData.b40_blk) CertData.b41_blk) CertData.b42_blk) CertData.b43_blk) CertData.b44_blk) CertData.b45_blk) CertData.b46_blk) CertData.b47_blk) CertData.b48_blk) CertData.b49_blk) CertData.b50_blk) CertData.b51_blk) CertData.b52_blk) CertData.b53_blk) CertData.b54_blk) CertData.b55_blk) CertData.b56_blk) CertData.b57_blk) CertData.b58_blk) CertData.b59_blk
  refine ⟨h.1, h.2.1, h.2.2.trans (le_of_eq ?_)⟩
  unfold stepBound
  norm_num

end Zeta35.Den
