"""Generate the Lean data files `RequestProject/Zeta35/CertData/B<k>.lean` from
`certificates/cert_c_p3_q4_d1_a1.5_k6.0.json` (zeta_3(5), N Theorem 5.1 certificate).

Each subcell [a, b] with (lam, h) becomes a record (b, lam, h, q, br, [S0_0..S0_3]) where
q = floor(3/u) on the subcell, br is the circle-model branch and S0_i is a maximiser of
V(N_i, b_i, S) - lam*S for the four class types (q+1,1), (q+1,0), (q,1), (q,0).
The Lean side re-checks everything (`Zeta35.Den.subOK`) by `decide +kernel`."""
import json, math, os, sys
from fractions import Fraction as F

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CERT = os.path.join(ROOT, 'certificates', 'cert_c_p3_q4_d1_a1.5_k6.0.json')
OUT = os.path.join(ROOT, 'RequestProject', 'Zeta35', 'CertData')
BLOCK = int(sys.argv[1]) if len(sys.argv) > 1 else 48

def V(N, b, S):
    if N == 1 and b == 1: return 0
    return 4*N*S + 3*min(S, 4*max(N-b, 0)) - S*S

def argmax_psi(N, b, lam):
    vals = [V(N, b, S) - lam*S for S in range(4*N+1)]
    m = max(vals); return vals.index(m)

def sgn(q, u):
    return 3 - (q + F(2, 3))*u if q % 2 == 0 else 3 - (q + F(1, 3))*u

def q_of(a, b):
    q = int(3 / ((a + b) / 2))
    assert q*b <= 3 <= (q+1)*a
    return q

def lit(x):
    x = F(x)
    return str(x.numerator) if x.denominator == 1 else f'{x.numerator}/{x.denominator}'

def main():
    C = json.load(open(CERT))
    # sanity check (not needed for soundness): the class values V(N, b, S) used in Lean coincide
    # with the certificate's tables V_c for every type of every cell
    for c in C['cells']:
        for t in c['types']:
            N = len(t['nodes']); b = sum(1 for x in t['nodes'] if x[3] == 0)
            assert all(V(N, b, S) == v for S, v in enumerate(t['V'])), (N, b)
    subs = [s for c in C['cells'] for s in c['subcells']]
    recs = []
    for s in subs:
        a, b, lam, h = F(s['a']), F(s['b']), F(s['lam']), F(s['h'])
        q = q_of(a, b)
        br = sgn(q, a) >= 0 and sgn(q, b) >= 0
        types = [(q+1, 1), (q+1, 0), (q, 1), (q, 0)]
        S0 = [argmax_psi(N, bb, lam) for (N, bb) in types]
        recs.append((a, b, lam, h, q, br, S0))
    os.makedirs(OUT, exist_ok=True)
    blocks = [recs[i:i+BLOCK] for i in range(0, len(recs), BLOCK)]
    names = []
    total = F(0)
    for k, blk in enumerate(blocks):
        a0 = blk[0][0]; last = blk[-1][1]
        ssum = sum(r[3]*(r[1]-r[0]) for r in blk)
        total += ssum
        S = F(math.ceil(ssum * 10**12), 10**12)
        name = f'b{k}'
        names.append((name, a0, last, S))
        lines = [f'import RequestProject.Zeta35.DenCertCheck', '',
                 f'/-! Generated by `scripts/gen_cert_c35.py` from `certificates/cert_c_p3_q4_d1_a1.5_k6.0.json`:',
                 f'subcells {k*BLOCK}–{k*BLOCK+len(blk)-1} (records `(b, λ, h, q, br, S₀)`), checked by kernel',
                 f'evaluation (`decide +kernel`). -/', '',
                 'namespace Zeta35.Den.CertData', '',
                 'set_option maxRecDepth 100000 in',
                 'set_option maxHeartbeats 0 in',
                 '/-- Subcell records. -/',
                 f'def {name} : List SubRec := [']
        for j, (a, b, lam, h, q, br, S0) in enumerate(blk):
            sep = ',' if j < len(blk)-1 else ']'
            lines.append(f'  ({lit(b)}, {lit(lam)}, {lit(h)}, {q}, {"true" if br else "false"}, [{", ".join(map(str, S0))}]){sep}')
        lines += ['',
                  'set_option maxRecDepth 100000 in',
                  f'theorem {name}_ok : chainOK ({lit(a0)}) {name} = true := by decide +kernel', '',
                  'set_option maxRecDepth 100000 in',
                  f'theorem {name}_last : lastB ({lit(a0)}) {name} = {lit(last)} := by decide +kernel', '',
                  'set_option maxRecDepth 100000 in',
                  f'theorem {name}_sum : stepSum ({lit(a0)}) {name} ≤ {lit(S)} := by decide +kernel', '',
                  f'theorem {name}_blk : Blk ({lit(a0)}) {name} ({lit(last)}) ({lit(S)}) :=',
                  f'  ⟨{name}_ok, {name}_last, {name}_sum⟩', '',
                  'end Zeta35.Den.CertData', '']
        open(os.path.join(OUT, f'B{k}.lean'), 'w').write('\n'.join(lines))
    # summary for the assembly file
    Stot = sum(x[3] for x in names)
    print(len(recs), len(blocks), float(total), lit(Stot), float(Stot))
    json.dump([(n, lit(a0), lit(l), lit(S)) for (n, a0, l, S) in names], open('/tmp/blocks.json', 'w'))

main()

def gen_main():
    names = json.load(open('/tmp/blocks.json'))
    imports = '\n'.join(f'import RequestProject.Zeta35.CertData.B{k}' for k in range(len(names)))
    lst = ' ++ '.join(n for (n, _, _, _) in names)
    Stot = sum(F(S) for (_, _, _, S) in names)
    first_a = names[0][1]; last_b = names[-1][2]
    chain = f'CertData.{names[0][0]}_blk'
    for (n, _, _, _) in names[1:]:
        chain = f'blk_app ({chain}) CertData.{n}_blk'
    body = f'''{imports}

/-!
# The certificate of N, Theorem 5.1 (generated by `scripts/gen_cert_c35.py`)

`certL` is the full list of the {sum(1 for _ in names)} kernel-checked blocks of subcells, covering
`[{first_a}, {last_b}]`; **`certL_blk`**: the chain is checked, ends at `{last_b}`, and its step sum
`∑ h (b − a)` is at most `stepBound = {lit(Stot)}` (≈ {float(Stot):.9f}).
-/

namespace Zeta35.Den

open CertData

/-- The full certificate. -/
def certL : List SubRec := {lst}

/-- The bound on the step sum `∑ h_i (b_i − a_i)`. -/
def stepBound : ℚ := {lit(Stot)}

set_option maxRecDepth 100000 in
/-- **The certificate is checked.** -/
theorem certL_blk : Blk ({first_a}) certL ({last_b}) stepBound := by
  have h := {chain}
  refine ⟨h.1, h.2.1, h.2.2.trans (le_of_eq ?_)⟩
  unfold stepBound
  norm_num

end Zeta35.Den
'''
    open(os.path.join(ROOT, 'RequestProject', 'Zeta35', 'DenCertC.lean'), 'w').write(body)

gen_main()
